name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: [ self-hosted, large ]
    container: bolt-ci:latest
    steps:
    - name: Cache ccache
      id: cache-ccache
      uses: corca-ai/local-cache@v3
      with:
        path: ~/.ccache
        key: ${{ runner.os }}-ccache-${{ hashFiles('**/conanfile.py') }}
        base: /tmp/actions-cache

    - name: Cache Conan2 packages
      id: cache-conan
      uses: corca-ai/local-cache@v3
      with:
        path: ~/.conan2/p
        key: ${{ runner.os }}-conan-${{ hashFiles('**/conanfile.py') }}
        base: /tmp/actions-cache

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Bolt dependencies
      run: |
        source ~/.profile
        ./scripts/install-bolt-deps.sh

    - name: Bolt Build
      run: |
        source ~/.profile
        # Build with tests enabled
        make release_with_test

    - name: Run tests
      run: |
        source ~/.profile
        # Run tests with output on failure
        make unittest_release