name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: [ self-hosted, large ]
    container: bolt-registry:5000/bolt-ci:latest
    strategy:
      matrix: 
        build_type: [ release, debug ]
    steps:
    - name: Checkout code
      uses: actions/checkout@v6
    - name: Add CI conan remote
      run: |
        source ~/.profile
        conan remote add ci https://bolt-registry:9300 --insert 0
      
    - name: Install Bolt dependencies
      run: |
        source ~/.profile
        ./scripts/install-bolt-deps.sh

    - name: Bolt Build
      run: |
        source ~/.profile
        make ${{ matrix.build_type }}_with_test

    - name: Run tests
      run: |
        source ~/.profile
        make unittest_${{ matrix.build_type }}
